quarkus.http.port=8081
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/pharma_users?createDatabaseIfNotExist=true

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
mp.jwt.verify.issuer=https://pharma-ecommerce.com
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem

quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

quarkus.log.console.enable=true
quarkus.log.console.level=INFO
quarkus.log.category."com.pharma".level=DEBUG

# OTP Configuration
pharma.otp.expiration-minutes=10
pharma.otp.length=6

# Gmail SMTP Configuration
quarkus.mailer.from=londheashish323@gmail.com
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.starttls=true
quarkus.mailer.auth=true
quarkus.mailer.username=londheashish323@gmail.com
quarkus.mailer.password=fqpqvervvyoewgvx
quarkus.mailer.mock=false

# Frontend URL Configuration
quarkus.frontend.url=http://localhost:3000
